MONBELL_COLOR_DICT = {
    "象牙色": ["IV"],
    "象牙白": ["IV"],
    "海军蓝": ["NV"],
    "蓝绿色": ["BGN"],
    "深蓝色": ["BGN"],
    "深绿色": ["DGN", "BGN"],
    "雾绿": ["DGN"],
    "白色": ["WT"],
    "素白": ["BOWT"],
    "雾白": ["WTSM"],
    "酒红色": ["WRD"],
    "深海军蓝": ["BKNV", "DKNV"],
    "深灰色": ["DGY", "GB/BN"],
    "棕褐色": ["TN"],
    "钴蓝色": ["CBL"],
    "浅灰色": ["LGY", "DGY"],
    "黑色24": ["BK24"],
    "深橄榄": ["BKOV"],
    "深棕色": ["DBN", "DBN-C"],
    "茄紫色": ["EP"],
    "黑蓝色": ["BLBK"],
    "波尔多红": ["BORD"],
    "砖红色": ["BRIC"],
    "深炭色": ["DKCH"],
    "铁灰色": ["GM", "GM-C"],
    "卡其棕色": ["KHBN"],
    "黄色24": ["YL24"],
    "紫色": ["PU"],
    "浅蓝色": ["LBL", "LBL25", "TQ"],
    "松石蓝": ["TQ"],
    "卡其色": ["KH", "OVGN"],
    "灰色": ["GY", "SV"],
    "灰蓝色": ["GY", "LBL"],
    "午夜蓝": ["MIDN"],
    "深红色": ["DRD"],
    "猎人绿": ["HTGN"],
    "珊瑚粉": ["CPK"],
    "石墨色": ["GRPH"],
    "靛蓝色": ["IND"],
    "墨蓝色": ["IKBL"],
    "浅褐色": ["LTN"],
    "薰衣草": ["LV"],
    "橄榄色": ["OV"],
    "橄榄棕": ["BNOV"],
    "石南灰": ["HC/GM"],
    "银色": ["SV"],
    "水手蓝": ["SLBL"],
    "橙红色": ["OGRD"],
    "米白": ["OTML"],
    "不锈钢色": ["DGY"],
    "谭": ["TN"],
    "原色蓝": ["PRBL"],
    "石板色": ["SLAT"],
    "淡靛蓝": ["PID-C"],
    "品蓝色": ["RBL"],
    "纯靛蓝": ["PUID"],
    "铁灰/宝石蓝": ["GM/BS"],
    "黑色/深蓝绿": ["BK/DT"],
    "浅蓝/靛蓝": ["LB/ID"],
    "孔雀蓝": ["PEBL"],
    "石板蓝": ["STBL"],
    "浅卡其/褐色": ["LK/TN"],
    "纯黑色": ["TRBK"],
    "暗灰": ["SHAD"],
    "辣椒红": ["PAP-C", "PAPRIC", "PAPRI"],
    "橙色24": ["OG24"],
    "摩尔灰": ["ML-C"],
    "浅卡其": ["LTKH"],
    "森林绿": ["FOST"],
    "暗绿色": ["DUGN"],
    "深褐色": ["DKSP"],
    "深青色": ["DKMA"],
    "沙土棕/铁灰": ["BS/GM"],
    "沙土棕": ["BNSD"],
    "黑色": ["BK"],
    "绿色": ["DGN", "GN"],
    "红色": ["RD"],
    "蓝色": ["BL"],
    "橙色": ["OG"],
    "棕色": ["BN"],
    "黄色": ["YL"],
}


def montbell_color_convert(color):
    result = None
    for key, value in MONBELL_COLOR_DICT.items():
        if key in color:
            result = value
            break
    return result
