# shop_no
MONBELL_SHOP_NO_SHINJUKU = 618937
MONBELL_SHOP_NO_IKEBUKURO = 678596
LULULEMON_SHOP_NO_OSD = 49124
LULULEMON_SHOP_NO_M = 49184
LULULEMON_SHOP_NO_TSM = 49181
LULULEMON_SHOP_NO_TAH = 49182
LULULEMON_SHOP_NO_TSHT = 49122
PATAGONIA_SHOP_NO_004 = '004'
PATAGONIA_SHOP_NO_005 = '005'
PATAGONIA_SHOP_NO_007 = '007'
PATAGONIA_SHOP_NO_012 = '012'
PATAGONIA_SHOP_NO_021 = '021'
PATAGONIA_SHOP_NO_028 = '028'
# shop_name
MONBELL_SHOP_NAME_SHINJUKU = 'モンベル 新宿南口店'
MONBELL_SHOP_NAME_IKEBUKURO = 'モンベル 池袋東武店'
LULULEMON_SHOP_NAME_OSD = 'Osaka Shinsaibashi Daimaru'
LULULEMON_SHOP_NAME_M = 'Midosuji'
LULULEMON_SHOP_NAME_TSM = 'Tokyo Shinjuku Marui'
LULULEMON_SHOP_NAME_TAH = 'Tokyo Azabudai Hills'
LULULEMON_SHOP_NAME_TSHT = 'Tokyo SIX HARAJUKU TERRACE'
PATAGONIA_SHOP_NAME_004 = 'パタゴニア 東京・渋谷'
PATAGONIA_SHOP_NAME_007 = 'パタゴニア 東京・神田'
PATAGONIA_SHOP_NAME_012 = 'パタゴニア サーフ東京／アウトレット'
PATAGONIA_SHOP_NAME_021 = 'パタゴニア 東京・丸の内'
PATAGONIA_SHOP_NAME_028 = 'パタゴニア 大阪・梅田'
# no_name_dict
MONBELL_SHOP_DICT = {MONBELL_SHOP_NO_SHINJUKU: MONBELL_SHOP_NAME_SHINJUKU,
                     MONBELL_SHOP_NO_IKEBUKURO: MONBELL_SHOP_NAME_IKEBUKURO}
LULULEMON_SHOP_DICT = {LULULEMON_SHOP_NO_OSD: LULULEMON_SHOP_NAME_OSD, LULULEMON_SHOP_NO_M: LULULEMON_SHOP_NAME_M,
                       LULULEMON_SHOP_NO_TSM: LULULEMON_SHOP_NAME_TSM, LULULEMON_SHOP_NO_TAH: LULULEMON_SHOP_NAME_TAH,
                       LULULEMON_SHOP_NO_TSHT: LULULEMON_SHOP_NAME_TSHT}
PATAGONIA_SHOP_DICT = {PATAGONIA_SHOP_NO_004: PATAGONIA_SHOP_NAME_004, PATAGONIA_SHOP_NO_007: PATAGONIA_SHOP_NAME_007,
                       PATAGONIA_SHOP_NO_012: PATAGONIA_SHOP_NAME_012, PATAGONIA_SHOP_NO_021: PATAGONIA_SHOP_NAME_021, PATAGONIA_SHOP_NO_028: PATAGONIA_SHOP_NAME_028}
