# TIANMAO_COLUMN_INDEX = {"title": 0, "model": 1, "sku": 2, "upc_barcode_ean": 3, "brand": 4, "size": 5, "url": 6,
#                         "msrp": 7, "discounted_price": 8, "product_main_image": 9, "product_other_image": 10,
#                         "description": 11, "product_spec": 12, "material": 13, "weight": 14, "dimension": 15,
#                         "color": 16, "stock_status": 17, "quantity": 18, "92折扣价": 19, "结果": 20
#                         }
TIANMAO_COLUMN_INDEX = {"model": 0, "size": 1, "msrp": 2, "discounted_price": 3, "color": 4, "quantity": 5, "结果": 6}
TIANMAO_COLUMN_REVERSE_INDEX = {v: k for k, v in TIANMAO_COLUMN_INDEX.items()}
DEWU_COLUMN_INDEX = {"出价ID": 0,
                    "SPU ID": 1,
                    "SKU ID": 2,
                    "三级类目": 3,
                    "品牌": 4,
                    "条形码": 5,
                    "商品名称": 6,
                    "货号": 7,
                    "规格": 8,
                    "总库存数": 9,
                    "在售数量": 10,
                    "待出价数量": 11,
                    "发货时效（天）": 12,
                    "我的出价(JPY)": 13,
                    "采购成本(JPY)": 14,
                    "经营成本(JPY)": 15,
                    "预计收入(JPY)": 16,
                    "预计毛利(JPY)": 17,
                    "预计净利(JPY)": 18,
                    "消费者是否可见": 19,
                    "*修改后发货时效（天）": 20,
                    "*修改后出价(JPY)": 21,
                    "*修改后库存": 22,
                    "露出价-价格(JPY)": 23,
                    "露出价-预计收入(JPY)": 24,
                    "露出价-预计毛利(JPY)": 25,
                    "露出价-预计净利(JPY)": 26,
                    "露出价-预计30天销量": 27,
                    "动销价-价格(JPY)": 28,
                    "动销价-预计收入(JPY)": 29,
                    "动销价-预计毛利(JPY)": 30,
                    "动销价-预计净利(JPY)": 31,
                    "动销价-预计30天销量": 32,
                    "近30日中国销量": 33,
                    "近30日中国成交均价": 34,
                    "近30日中国最高成交价": 35,
                    "近30日中国最低成交价": 36,
                    "结果": 37
                     }
DEWU_COLUMN_REVERSE_INDEX = {v: k for k, v in DEWU_COLUMN_INDEX.items()}
